export const LOAD_COMPANIES = 'LOAD_COMPANIES';
export const LOAD_COMPANIES_STARTED = 'LOAD_COMPANIES_STARTED';
export const LOAD_COMPANIES_SUCCESS = 'LOAD_COMPANIES_SUCCESS';
export const LOAD_COMPANIES_FAILED = 'LOAD_COMPANIES_FAILED';
export const LOAD_COMPANY_EDIT_FORM = 'LOAD_COMPANY_EDIT_FORM';
